apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: 28
  labels:
    alertmanagerConfig: default
spec:
  route:
    groupBy: ['...']
    receiver: 'default-receiver'
    routes:
    - receiver: 28
      groupWait: 10s
      matchers:
      - name: feed
