name: Playout Orchastrator

on:
  workflow_dispatch:
    inputs:
      config:
        description: 'provide charts content'
        default: 'config.yaml'
        required: true
      directory:
        description: 'Directory where the file will be saved(please do not provide slash "/" in start and end)'
        default: 'dev/sample-directory'
        required: true
      branch:
        description: 'Branch name'
        default: 'playouts-dev'
        required: true

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }}
    - name: Initiating workflow
      run: echo "Initiating workflow"
    - name: Creating directory in branch
      run: |
          echo "creating directory ${{ github.event.inputs.directory }}"
          mkdir -p ${{ github.event.inputs.directory }}
          echo "Adding files to directory"
    - name: Creating file
      run: |
        if [ "${{ github.event.inputs.charts }}" != "Charts.yaml" ]
        then
          echo "${{ github.event.inputs.chart }}" > ${{ github.event.inputs.directory }}/Chart.yaml
        fi
        if [ "${{ github.event.inputs.app }}" != "app.yaml" ]
        then
          echo "${{ github.event.inputs.app }}" > ${{ github.event.inputs.directory }}/app.yaml
        fi
        if [ "${{ github.event.inputs.dev-values }}" != "dev-values.yaml" ]
        then
          echo "${{ github.event.inputs.dev-values }}" > ${{ github.event.inputs.directory }}/dev-values.yaml
        fi
        if [ "${{ github.event.inputs.dev_values }}" != "dev_values.yaml" ]
        then
          echo "${{ github.event.inputs.dev_values }}" > ${{ github.event.inputs.directory }}/dev_values.yaml
        fi
        if [ "${{ github.event.inputs.override_values }}" != "override_values.yaml" ]
        then
          echo "${{ github.event.inputs.override_values }}" > ${{ github.event.inputs.directory }}/override_values.yaml
        fi
        if [ "${{ github.event.inputs.ops_config }}" != "ops_config.ini" ]
        then
          echo "${{ github.event.inputs.ops_config }}" > ${{ github.event.inputs.directory }}/ops_config.ini
        fi
        if [ "${{ github.event.inputs.values }}" != "values.yaml" ]
        then
          echo "${{ github.event.inputs.values }}" > ${{ github.event.inputs.directory }}/values.yaml
        fi
    - name: git config
      run: |
        git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
        git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
    - name: git add, commit and push
      run: |
        git add .
        git commit -m "Added new file at ${{ github.event.inputs.directory }}"
        git push
    - name: Workflow completion
      run: echo "Task completed. File Created at ${{ github.event.inputs.directory }}"
